from __future__ import annotations

from bili_recipe_notes.subtitle import parse_srt, parse_vtt


def test_parse_vtt_accepts_optional_hours_cue_ids_and_settings() -> None:
    content = """\ufeffWEBVTT
Kind: captions
Language: zh

intro-cue
00:01.250 --> 00:03.500 align:start position:10%
先切番茄

42
01:02:03.000 --> 01:02:05.250 line:90%
然后下锅翻炒
"""

    segments = parse_vtt(content)

    assert [(segment.start, segment.end, segment.text) for segment in segments] == [
        (1.25, 3.5, "先切番茄"),
        (3723.0, 3725.25, "然后下锅翻炒"),
    ]


def test_parse_srt_accepts_non_numeric_cue_id_and_skips_malformed_blocks() -> None:
    content = """NOTEworthy-cue-id
00:00:01,000 --> 00:00:02,000
准备鸡蛋

broken
not a timing line
ignored

scene-b
00:02.000 --> 00:04.000 position:20%
下锅翻炒
"""

    segments = parse_srt(content)

    assert [segment.text for segment in segments] == ["准备鸡蛋", "下锅翻炒"]


def test_parse_vtt_ignores_note_style_and_empty_cues() -> None:
    content = """WEBVTT

NOTE generated by test
00:00.000 --> 00:01.000
not a cue

STYLE
::cue { color: lime; }

empty
00:01.000 --> 00:02.000

valid
00:02.000 --> 00:03.000
加盐
"""

    assert [segment.text for segment in parse_vtt(content)] == ["加盐"]
